/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tix.main;

import com.tix.dashboard.Home;
import com.tix.event.MenuEvent;
import com.tix.home.forms.HomeForm;
import com.tix.home.staff.StaffForm;
import com.tix.home.forms.VehiclesForm;
import com.tix.home.staff.RegisterForm;
import com.tix.event.ButtonEvent;
import com.tix.login.Login;
import javax.swing.JPanel;

/**
 *
 * @author Germanchoo
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        this.home = new Home();
        this.login = new Login();
        this.homeForm = new HomeForm();
        this.staffForm = new StaffForm();
        this.registerForm = new RegisterForm();
        this.vehiclesForm = new VehiclesForm();

        initComponents();

        setLocationRelativeTo(null);
        setLayout(null);
        showFrame(login, 800, 450, 0);

        login.addEventMenuSelected((int index) -> {
            showFrame(home, 900, 500, 860);
        });

        home.addEventMenuSelected((int index) -> {
            switch (index) {
                case 0 ->
                    home.showForm(homeForm);
                case 1 ->
                    home.showForm(staffForm);
                case 2 ->
                    home.showForm(vehiclesForm);
                case 3 ->
                    showFrame(login, 800, 450, 0);
            }
        });

        staffForm.addEventButtonSelected((int index) -> {
            switch (index) {
                case 0 ->
                    home.showForm(registerForm);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new com.tix.main.Header();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    private void showFrame(JPanel panel, int width, int height, int exitButtonAlignment) {
        setSize(width, height);
        header.setSize(width, 40);
        mainPanel.setSize(width, height);
        header.getExitButton().setBounds(exitButtonAlignment, 0, 40, 40);
        mainPanel.removeAll();
        mainPanel.add(panel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    public void addEventMenuSelected(MenuEvent event) {
        this.event = event;
        login.addEventMenuSelected(event);
    }
    private MenuEvent event;

    public void addEventButtonSelected(ButtonEvent buttonEvent) {
        this.buttonEvent = buttonEvent;
        staffForm.addEventButtonSelected(buttonEvent);
    }
    private ButtonEvent buttonEvent;

    private final VehiclesForm vehiclesForm;
    private StaffForm staffForm;
    private RegisterForm registerForm;
    private HomeForm homeForm;
    private final Login login;
    private Home home;

    private int xMouse, yMouse;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.tix.main.Header header;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
