/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tix.dashboard.components;

import java.awt.Color;

/**
 *
 * @author Germanchoo
 */
public class MenuButton extends javax.swing.JPanel {

    /**
     * Creates new form MenuButton
     */
    public MenuButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardButton = new javax.swing.JButton();
        staffButton = new javax.swing.JButton();
        vehiclesButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        dashboardButton.setBackground(new java.awt.Color(255, 255, 255));
        dashboardButton.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        dashboardButton.setForeground(new java.awt.Color(51, 51, 51));
        dashboardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tix/images/dashboard/1.png"))); // NOI18N
        dashboardButton.setText("Dashboard");
        dashboardButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        dashboardButton.setBorderPainted(false);
        dashboardButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardButton.setFocusable(false);
        dashboardButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashboardButton.setIconTextGap(10);
        dashboardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dashboardButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dashboardButtonMouseReleased(evt);
            }
        });

        staffButton.setBackground(new java.awt.Color(255, 255, 255));
        staffButton.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        staffButton.setForeground(new java.awt.Color(51, 51, 51));
        staffButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tix/images/dashboard/2.png"))); // NOI18N
        staffButton.setText("Staff");
        staffButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        staffButton.setBorderPainted(false);
        staffButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        staffButton.setFocusable(false);
        staffButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        staffButton.setIconTextGap(10);
        staffButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                staffButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                staffButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                staffButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                staffButtonMouseReleased(evt);
            }
        });

        vehiclesButton.setBackground(new java.awt.Color(255, 255, 255));
        vehiclesButton.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        vehiclesButton.setForeground(new java.awt.Color(51, 51, 51));
        vehiclesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tix/images/dashboard/3.png"))); // NOI18N
        vehiclesButton.setText("Vehicles");
        vehiclesButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        vehiclesButton.setBorderPainted(false);
        vehiclesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vehiclesButton.setFocusable(false);
        vehiclesButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vehiclesButton.setIconTextGap(10);
        vehiclesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vehiclesButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vehiclesButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vehiclesButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                vehiclesButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                vehiclesButtonMouseReleased(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(255, 255, 255));
        logoutButton.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(51, 51, 51));
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tix/images/dashboard/key.png"))); // NOI18N
        logoutButton.setText("Log out");
        logoutButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        logoutButton.setBorderPainted(false);
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.setFocusable(false);
        logoutButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logoutButton.setIconTextGap(10);
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logoutButtonMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(staffButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
            .addComponent(vehiclesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
            .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(dashboardButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(staffButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vehiclesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutButton)
                .addContainerGap(175, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardButtonMouseEntered
        dashboardButton.setBackground(new Color(225, 225, 225));
    }//GEN-LAST:event_dashboardButtonMouseEntered

    private void dashboardButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardButtonMouseExited
        dashboardButton.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_dashboardButtonMouseExited

    private void dashboardButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardButtonMousePressed
        dashboardButton.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_dashboardButtonMousePressed

    private void dashboardButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardButtonMouseReleased
        dashboardButton.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_dashboardButtonMouseReleased

    private void dashboardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardButtonMouseClicked
    }//GEN-LAST:event_dashboardButtonMouseClicked

    private void staffButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffButtonMouseClicked

    }//GEN-LAST:event_staffButtonMouseClicked

    private void staffButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffButtonMouseEntered
        staffButton.setBackground(new Color(225, 225, 225));
    }//GEN-LAST:event_staffButtonMouseEntered

    private void staffButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffButtonMouseExited
        staffButton.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_staffButtonMouseExited

    private void staffButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffButtonMousePressed
        staffButton.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_staffButtonMousePressed

    private void staffButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffButtonMouseReleased
        staffButton.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_staffButtonMouseReleased

    private void vehiclesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehiclesButtonMouseClicked

    }//GEN-LAST:event_vehiclesButtonMouseClicked

    private void vehiclesButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehiclesButtonMouseEntered
        vehiclesButton.setBackground(new Color(225, 225, 225));
    }//GEN-LAST:event_vehiclesButtonMouseEntered

    private void vehiclesButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehiclesButtonMouseExited
        vehiclesButton.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_vehiclesButtonMouseExited

    private void vehiclesButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehiclesButtonMousePressed
        vehiclesButton.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_vehiclesButtonMousePressed

    private void vehiclesButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehiclesButtonMouseReleased
        vehiclesButton.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_vehiclesButtonMouseReleased

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        //MechanicalWorkshop.loginUI.setVisible(true);
        //MechanicalWorkshop.loginUI.dashboardFrame.setVisible(false);
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void logoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseEntered
        logoutButton.setBackground(new Color(225, 225, 225));
    }//GEN-LAST:event_logoutButtonMouseEntered

    private void logoutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseExited
        logoutButton.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_logoutButtonMouseExited

    private void logoutButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMousePressed
        logoutButton.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_logoutButtonMousePressed

    private void logoutButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseReleased
        logoutButton.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_logoutButtonMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dashboardButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton staffButton;
    private javax.swing.JButton vehiclesButton;
    // End of variables declaration//GEN-END:variables
}
