/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tix.dashboard;

import com.tix.dashboard.event.MenuEvent;
import javax.swing.JPanel;

/**
 *
 * @author Germanchoo
 */
public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formPanel = new javax.swing.JPanel();
        menu = new com.tix.dashboard.components.Menu();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formPanel.setBackground(new java.awt.Color(255, 255, 255));
        formPanel.setLayout(new java.awt.BorderLayout());
        add(formPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 750, 450));
        add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    public void addEventMenuSelected(MenuEvent event) {
        this.event = event;
        menu.addEventMenuSelected(event);
    }

    public void showForm(JPanel panel) {
        formPanel.removeAll();
        formPanel.add(panel);
        formPanel.repaint();
        formPanel.revalidate();
    }

    private MenuEvent event;
    private int xMouse, yMouse;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel formPanel;
    private com.tix.dashboard.components.Menu menu;
    // End of variables declaration//GEN-END:variables
}
