/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tix.dashboard;

import com.tix.login.LoginUI;
import java.awt.Color;

/**
 *
 * @author Germanchoo
 */
public class MenuBar extends javax.swing.JPanel {

    /**
     * Creates new form ManuBar
     */
    public MenuBar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardButton = new javax.swing.JButton();
        stuffButton = new javax.swing.JButton();
        vehiclesButton = new javax.swing.JButton();
        statisticsButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        dashboardButton.setBackground(new java.awt.Color(255, 255, 255));
        dashboardButton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        dashboardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tix/images/dashboard/1.png"))); // NOI18N
        dashboardButton.setText("Dashboard");
        dashboardButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        dashboardButton.setBorderPainted(false);
        dashboardButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardButton.setFocusable(false);
        dashboardButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashboardButton.setIconTextGap(10);
        dashboardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonMouseReleased(evt);
            }
        });

        stuffButton.setBackground(new java.awt.Color(255, 255, 255));
        stuffButton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        stuffButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tix/images/dashboard/2.png"))); // NOI18N
        stuffButton.setText("Stuff");
        stuffButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        stuffButton.setBorderPainted(false);
        stuffButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stuffButton.setFocusable(false);
        stuffButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stuffButton.setIconTextGap(10);
        stuffButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonMouseReleased(evt);
            }
        });

        vehiclesButton.setBackground(new java.awt.Color(255, 255, 255));
        vehiclesButton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        vehiclesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tix/images/dashboard/3.png"))); // NOI18N
        vehiclesButton.setText("Vehicles");
        vehiclesButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        vehiclesButton.setBorderPainted(false);
        vehiclesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vehiclesButton.setFocusable(false);
        vehiclesButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vehiclesButton.setIconTextGap(10);
        vehiclesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonMouseReleased(evt);
            }
        });

        statisticsButton.setBackground(new java.awt.Color(255, 255, 255));
        statisticsButton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        statisticsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tix/images/dashboard/7.png"))); // NOI18N
        statisticsButton.setText("Statistics");
        statisticsButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        statisticsButton.setBorderPainted(false);
        statisticsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statisticsButton.setFocusable(false);
        statisticsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statisticsButton.setIconTextGap(10);
        statisticsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonMouseReleased(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(255, 255, 255));
        logoutButton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tix/images/dashboard/key.png"))); // NOI18N
        logoutButton.setText("Log out");
        logoutButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        logoutButton.setBorderPainted(false);
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.setFocusable(false);
        logoutButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logoutButton.setIconTextGap(10);
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statisticsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehiclesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stuffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(dashboardButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stuffButton)
                .addGap(12, 12, 12)
                .addComponent(vehiclesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statisticsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutButton)
                .addContainerGap(215, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseEntered
        if(evt.getSource().equals(dashboardButton)) dashboardButton.setBackground(new Color(224,224,224));
        if(evt.getSource().equals(stuffButton)) stuffButton.setBackground(new Color(224,224,224));
        if(evt.getSource().equals(vehiclesButton)) vehiclesButton.setBackground(new Color(224,224,224));
        if(evt.getSource().equals(statisticsButton)) statisticsButton.setBackground(new Color(224,224,224));
        if(evt.getSource().equals(logoutButton)) logoutButton.setBackground(new Color(224,224,224));
    }//GEN-LAST:event_buttonMouseEntered

    private void buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseExited
        if(evt.getSource().equals(dashboardButton)) dashboardButton.setBackground(Color.white);
        if(evt.getSource().equals(stuffButton)) stuffButton.setBackground(Color.white);
        if(evt.getSource().equals(vehiclesButton)) vehiclesButton.setBackground(Color.white);
        if(evt.getSource().equals(statisticsButton)) statisticsButton.setBackground(Color.white);
        if(evt.getSource().equals(logoutButton)) logoutButton.setBackground(Color.white);
    }//GEN-LAST:event_buttonMouseExited

    private void buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMousePressed
        if(evt.getSource().equals(dashboardButton)) dashboardButton.setBackground(Color.LIGHT_GRAY);
        if(evt.getSource().equals(stuffButton)) stuffButton.setBackground(Color.LIGHT_GRAY);
        if(evt.getSource().equals(vehiclesButton)) vehiclesButton.setBackground(Color.LIGHT_GRAY);
        if(evt.getSource().equals(statisticsButton)) statisticsButton.setBackground(Color.LIGHT_GRAY);
        if(evt.getSource().equals(logoutButton)) logoutButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_buttonMousePressed

    private void buttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseReleased
        if(evt.getSource().equals(dashboardButton)) dashboardButton.setBackground(Color.white);
        if(evt.getSource().equals(stuffButton)) stuffButton.setBackground(Color.white);
        if(evt.getSource().equals(vehiclesButton)) vehiclesButton.setBackground(Color.white);
        if(evt.getSource().equals(statisticsButton)) statisticsButton.setBackground(Color.white);
        if(evt.getSource().equals(logoutButton)) logoutButton.setBackground(Color.white);
    }//GEN-LAST:event_buttonMouseReleased

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        setVisible(false);
        new LoginUI().setVisible(true);
    }//GEN-LAST:event_logoutButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dashboardButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton statisticsButton;
    private javax.swing.JButton stuffButton;
    private javax.swing.JButton vehiclesButton;
    // End of variables declaration//GEN-END:variables
}
